##This is just a template for CI/CD workflow.
##You can modify it according to your needs
name: Build, Push,Test and Deploy Resume

on:
    #workflow_dispatch: # This allows you to manually trigger the workflow from the GitHub Actions tab
    push:
        branches: [ main, dev]
    pull_request:
        branches: [ main ]

permissions:
    contents: read
    id-token: write # This is required for AWS OIDC authentication

env:
    # Define any environment variables here
    # For example:
    # NODE_ENV: production
    # API_KEY: ${{ secrets.API_KEY }}
    # GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    AWS_REGION: us-east-1
    AWS_ACTIONS_ROLE_ARN: ${{ secrets.AWS_ACTIONS_ROLE_ARN }}
    ECR_REPO_NAME: dev-test
    IMAGE_TAG: ${{ github.run_number }}
    ECS_CLUSTER: nginx-cluster
    ECS_SERVICE: nginx-service
    #ECS_TASK_DEFINITION: templates/td.json
    ECS_TASK_DEFINITION: nginx-task
    ECS_TASK_EXECUTION_ROLE: ${{ secrets.AWS_EXECUTION_ROLE_ARN }}
    container_name: nginx
    

jobs:
    build:
        runs-on: ubuntu-latest
        outputs:
            image-uri: ${{ steps.get-image-uri.outputs.image-uri }}
        steps:
            - name: clone-repo
              uses: actions/checkout@v4

            - name: aws-credentials-config
              uses: aws-actions/configure-aws-credentials@v5
              with:
                role-to-assume: ${{ env.AWS_ACTIONS_ROLE_ARN }}
                aws-region: ${{ env.AWS_REGION }}

            - name: ECR_login
              uses: aws-actions/amazon-ecr-login@v1
              id:   ecr-login
            
            - name: Echo Registry
              run: |
                echo 'My ECR Registry is: ${{ steps.ecr-login.outputs.registry }}'
                echo 'My ECR Repository Name is: ${{ env.ECR_REPO_NAME }}'

            - name: Pre scanning using trivy
              uses: aquasecurity/trivy-action@v0.20.0
              with:
                scan-type: 'fs' # Type of scan (fs for filesystem, image for container images)
                scan-ref: '.'   # Path to the directory containing the Dockerfile
                exit-code: '1'  # Exit with code 1 if vulnerabilities are found
                ignore-unfixed: true # Ignore vulnerabilities that do not have a fix available
                severity: 'CRITICAL' # Only fail the build if there are CRITICAL issues

            - name: Check Dockerfile
              run: |
                echo "Checking if Dockerfile exists in the expected location"
                ls -laR templates/Dockerfile

            - name: Build and Push Docker Image to ECR
              id:   build-image
              run:  | 
                echo "pushing image to ECR"
                ls -laR templates/Dockerfile ##to check if Dockerfile is present in the expected location
                echo "building docker image"
                echo "docker build -t ${{ steps.ecr-login.outputs.registry }}/${{ env.ECR_REPO_NAME }}:${{ env.IMAGE_TAG }} templates/"
                docker build -t ${{ steps.ecr-login.outputs.registry }}/${{ env.ECR_REPO_NAME }}:${{ env.IMAGE_TAG }} templates/

            - name: Post scanning using trivy
              uses: aquasecurity/trivy-action@master
              with:
                image-ref: ${{ steps.ecr-login.outputs.registry }}/${{ env.ECR_REPO_NAME }}:${{ env.IMAGE_TAG }}
                format: 'table' # Output format (table, json, etc.)
                exit-code: '0' # Exit with code 1 if vulnerabilities are found
                #just-audit: true # Only check for vulnerabilities that have a fix available
                severity: 'CRITICAL,HIGH' # Only fail the build if there are CRITICAL or HIGH vulnerabilities
                #severity: 'CRITICAL' # Only fail the build if there are CRITICAL issues
                ignore-unfixed: true # Ignore vulnerabilities that do not have a fix available
                

            - name: Push Docker Image to ECR
              id:   push-image
              run:  |
                    echo "Pushing docker image for ECR"
                    echo "docker push ${{ steps.ecr-login.outputs.registry }}/${{ env.ECR_REPO_NAME }}:${{ env.IMAGE_TAG }}" 
                    docker push ${{ steps.ecr-login.outputs.registry }}/${{ env.ECR_REPO_NAME }}:${{ env.IMAGE_TAG }} 
                    
            - name: Get ECR Image URI
              id:   get-image-uri
              run:  |
                    echo "Getting ECR Image URI"
                    IMAGE_URI=${{ steps.ecr-login.outputs.registry }}/${{ env.ECR_REPO_NAME }}:${{ env.IMAGE_TAG }}
                    echo "image-uri=${IMAGE_URI}" >> $GITHUB_OUTPUT
        
    deploy:
        needs: build
        runs-on: ubuntu-latest
        steps:
            #- name: clone-repo
            #  uses: actions/checkout@v4

            - name: aws-credentials-config
              uses: aws-actions/configure-aws-credentials@v5
              with:
                role-to-assume: ${{ env.AWS_ACTIONS_ROLE_ARN }}
                aws-region: ${{ env.AWS_REGION }}

            - name: Download Task Definition from ECS
              id: download-td
              run: |
                    echo "Downloading Task Definition from ECS"
                    #aws ecs describe-task-definition --task-definition ${{ env.ECS_TASK_DEFINITION }} --query 'taskDefinition' > task-def.json
                    aws ecs describe-task-definition --task-definition ${{ env.ECS_TASK_DEFINITION }} --query taskDefinition > task-definition.json

            - name: Update Task Definition with new image
              id: update-td
              run: |
                    echo "Updating Task Definition with new image"

                    IMAGE_URI="${{ needs.build.outputs.image-uri }}"
                    echo "New Image URI: $IMAGE_URI"

                    jq --arg IMAGE_URI "${{ needs.build.outputs.image-uri }}" '.containerDefinitions[0].image = $IMAGE_URI | 
                    del(.taskDefinitionArn, .revision, .status, .requiresAttributes, .compatibilities, .registeredAt, .registeredBy, .deregisteredAt)' task-definition.json > register-task-definition.json


            - name: Display updated Task Definition
              id: display-td
              run: |
                    echo "Updated Task Definition:"
                    cat register-task-definition.json

            - name: Register new task definition
              run: |
                    aws ecs register-task-definition --cli-input-json file://register-task-definition.json
                    echo "NEW_TASK_DEFINITION=$(aws ecs describe-task-definition --task-definition ${{ env.ECS_TASK_DEFINITION }} --query 'taskDefinition.taskDefinitionArn' --output text)" >> $GITHUB_ENV
      
            - name: Update ECS service
              run: |
                    aws ecs update-service --cluster ${{ env.ECS_CLUSTER }} --service ${{ env.ECS_SERVICE }} --task-definition ${{ env.NEW_TASK_DEFINITION }} --force-new-deployment            

            #- name: Register new Task Definition
            #  id: register-td
            #  run: |
            #        echo "Registering new Task Definition"
            #        aws ecs register-task-definition --cli-input-json file://updated-task-def.json
            #        echo "NEW_TASK_DEFINTION=$(aws ecs describe-task-definition --task-definition ${{ env.ECS_TASK_DEFINITION }} --query 'taskDefinition.taskDefinitionArn' --output text)" >> $GITHUB_ENV
            #        #aws ecs register-task-definition --cli-input-json file://updated-task-def.json

            #- name: Update ECS Service to use new Task Definition
            #  id: update-service
            #  run: |
            #        echo "Updating ECS Service to use new Task Definition"
            #        #aws ecs update-service --cluster ${{ env.ECS_CLUSTER }} --service ${{ env.ECS_SERVICE }} --task-definition ${{ env.NEW_TASK_DEFINITION }}} --force-new-deployment
            #        aws ecs update-service --cluster ${{ env.ECS_CLUSTER }} --service ${{ env.ECS_SERVICE }} --task-definition ${{ steps.register-td.outputs.task-definition }} --force-new-deployment

            #- name: Register new Task Definition
            #  id: register-td
            #  run: |
            #    aws ecs register-task-definition --cli-input-json file://register-task-definition.json
            #    NEW_TASK_DEF_ARN=$(aws ecs describe-task-definition \
            #      --task-definition ${{ env.ECS_TASK_DEFINITION }} \
            #      --query 'taskDefinition.taskDefinitionArn' --output text)
            #    echo "task-definition=${NEW_TASK_DEF_ARN}" >> $GITHUB_OUTPUT

            #- name: Update ECS Service to use new Task Definition
            #  run: |
            #    aws ecs update-service \
            #      --cluster ${{ env.ECS_CLUSTER }} \
            #      --service ${{ env.ECS_SERVICE }} \
            #      --task-definition ${{ steps.register-td.outputs.task-definition }} \
            #      --force-new-deployment

            #- name: Render ECS Task Definition
            #  id:   render-task-def
            #  uses: aws-actions/amazon-ecs-render-task-definition@v1
            #  with:
            #        task-definition: ${{ env.ECS_TASK_DEFINITION }}
            #        container-name: ${{ env.container_name }}
            #        image: ${{ needs.build.outputs.image-uri }}
               
            #- name: Deploy to Amazon ECS
            #  id:   deploy-ecs 
            #  uses: aws-actions/amazon-ecs-deploy-task-definition@v1
            #  with: 
            #        cluster: ${{ env.ECS_CLUSTER }}
            #        service: ${{ env.ECS_SERVICE }}
            #        task-definition: ${{ steps.render-task-def.outputs.task-definition }}