##This is just a template for CI/CD workflow.
##You can modify it according to your needs
name: Build, Push,Test and Deploy Resume

on:
    #workflow_dispatch: # This allows you to manually trigger the workflow from the GitHub Actions tab
    push:
        branches: [ main, dev]
    pull_request:
        branches: [ main ]

permissions:
    contents: read
    id-token: write # This is required for AWS OIDC authentication

env:
    # Define any environment variables here
    # For example:
    # NODE_ENV: production
    # API_KEY: ${{ secrets.API_KEY }}
    # GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    AWS_REGION: us-east-1
    AWS_ACTIONS_ROLE_ARN: ${{ secrets.AWS_ACTIONS_ROLE_ARN }}
    ECR_REPO_NAME: dev-test
    IMAGE_TAG: ${{ github.run_number }}


jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: clone-repo
              uses: actions/checkout@v4

            - name: aws-credentials-config
              uses: aws-actions/configure-aws-credentials@v5
              with:
                role-to-assume: ${{ env.AWS_ACTIONS_ROLE_ARN }}
                aws-region: ${{ env.AWS_REGION }}

            - name: ECR_login
              uses: aws-actions/amazon-ecr-login@v1
              id:   ecr-login
            
            - name: Echo Registry
              run: |
                echo 'My ECR Registry is: ${{ steps.ecr-login.outputs.registry }}'
                echo 'My ECR Repository Name is: ${{ env.ECR_REPO_NAME }}'

            - name: Build and Push Docker Image to ECR
              id:   build-and-push
              run:  | 
                echo "pushing image to ECR"
                ls -laR templates/Dockerfile ##to check if Dockerfile is present in the expected location
                echo "building docker image"
                docker build -t ${{ steps.ecr-login.outputs.ecr-registry }}${{ env.ECR_REPO_NAME }}:${{ env.IMAGE_TAG }} templates/
                echo "docker build -t ${{ steps.ecr-login.outputs.ecr-registry }}${{ env.ECR_REPO_NAME }}:${{ env.IMAGE_TAG }} templates/"
                echo "tagging docker image for ECR"
                echo "docker tag ${{ steps.ecr-login.outputs.ecr-registry }}${{ env.ECR_REPO_NAME }}:${{ env.IMAGE_TAG }}" 
                docker tag ${{ steps.ecr-login.outputs.ecr-registry }}${{ env.ECR_REPO_NAME }}:${{ env.IMAGE_TAG }} 

                # Build your Docker image here
                #docker build -t my-image-name:${{ github.run_number }} .
                
                # Tag the image for ECR
                #docker tag my-image-name:${{ github.run_number }} <aws_account_id>.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/my-image-name:${{ github.run_number }}
                
                # Push the image to ECR
                #docker push <aws_account_id>.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/my-image-name:${{ github.run_number }}
    #    needs: job1 # This means job2 will only run after job1 is completed
    #    runs-on: #some runner
    #    steps:
    #        - name: step1
    #          run: #some command
    #        - name: step2
    #          uses: #some action
    #        - name: step3
    #          run: #some command
    #          with:
    #            #some parameters
    #            param1: value1
    #            param2: value2
    #        - name: step4
    #          uses: #some action
    #          with:
    #            #some parameters
    #            param1: value1
    #            param2: value2